services:
  lms-service:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lms_service
    ports:
      - "8080:8080"
    restart: on-failure:5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 3