services:
  postgres:
    image: postgres:16
    container_name: lms_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: lms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lms_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  mongo:
    image: mongo:5.0
    container_name: lms_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'db.runCommand({ ping: 1 }).ok' | mongosh localhost:27017/test --quiet"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  lms-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lms_service
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: on-failure:5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      [
        "/app/lms_service",
        "--config", "/app/configs/static_config.yaml",
        "--config_vars", "/app/configs/config_vars.yaml"
      ]

volumes:
  postgres_data:
  mongo_data: